export function usageSectionSrc({jsx,useState,useEffect,card,zs,bar,barStyle}){return `
/* cursor-chatgpt-bridge: ChatGPT subscription usage section */
function __chatgptUsageSection(){
const __s1=${useState}(null),u=__s1[0],h=__s1[1],__s2=${useState}(null),g=__s2[0],f=__s2[1];
${useEffect}(()=>{let v=!0;const load=()=>fetch(__chatgptBridgeBase+"/usage",{headers:{Authorization:"Bearer "+__chatgptBridgeKey}}).then(r=>{if(!r.ok)throw new Error("HTTP "+r.status);return r.json()}).then(d=>{if(v){h(d);f(null)}}).catch(e2=>{if(v)f(String(e2&&e2.message||e2))});load();const id=setInterval(load,6e4);return()=>{v=!1;clearInterval(id)}},[]);
const fmt=w=>{if(!w)return"Not available";const m=Math.round(Math.max(0,w*1e3-Date.now())/6e4);if(m<1)return"in <1 min";if(m<60)return"in "+m+" min";const h=Math.round(m/60);if(h<48)return"in "+h+" h";return"in "+Math.round(h/24)+" d"};
const winLabel=w=>w.windowSeconds>=86400?Math.round(w.windowSeconds/86400)+"-day limit":Math.round(w.windowSeconds/3600)+"-hour limit";
const row=(label,w)=>w==null?[]:[${jsx}(${zs}.Entry,{label:winLabel(w),children:${jsx}("span",{className:"glass-fifm61 glass-19aaqeu",children:[Math.round(w.usedPercent),"% used"]})},label+"-e"),${jsx}(${zs}.Preview,{children:${jsx}("div",{className:"glass-78zum5 glass-dt5ytf glass-9f619 glass-h8yej3 glass-pkkfsy glass-exx8yu glass-1jkygx glass-usxwy5 glass-1o7kk3e",children:${jsx}(${bar},{"aria-label":label,style:${barStyle},value:Math.min(1,Math.max(0,(w.usedPercent||0)/100)),variant:"bar"})})},label+"-p"),${jsx}(${zs}.Entry,{label:"Next reset",children:${jsx}("span",{className:"glass-fifm61 glass-1yl5bsf glass-1wd3ewq",children:fmt(w.resetAt)})},label+"-r")];
return ${jsx}(${card},{title:"ChatGPT Subscription",description:"Usage of your ChatGPT subscription. Refreshes every minute.",children:${jsx}(${zs}.Root,{accessibleLabel:"ChatGPT subscription usage",children:g?${jsx}(${zs}.Entry,{label:"Status",children:${jsx}("span",{className:"glass-fifm61 glass-1yl5bsf glass-1wd3ewq",children:"Unavailable: "+g})}):u==null?${jsx}(${zs}.Entry,{label:"Status",children:${jsx}("span",{className:"glass-fifm61 glass-19aaqeu",children:"Loading..."})}):[${jsx}(${zs}.Entry,{label:"Plan",children:${jsx}("span",{className:"glass-fifm61 glass-19aaqeu",children:String(u.planType||"Not available")})},"plan"),...row("primary",u.primary),...row("secondary",u.secondary)]})});
}
`;}
